name: test
on: [push, pull_request]
env:
  CI: true
  NODE_VERSION: 22
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 18, 20, 22 ]
        os: [macos-latest, windows-latest, ubuntu-latest]
        exclude:
          # mac tests is expensive, limit to 1 instance
          - os: macos-latest
            node-version: 18
          # Tests appear to be failing for connectivity reasons
          - os: windows-latest
            node-version: 18
          # Regression bug in Node.js 22
          # https://github.com/nodejs/node/issues/51766
          - os: windows-latest
            node-version: 22
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run lint && pnpm test
      - name: Run E2E
        run: pnpm run build
        working-directory: examples/benchmark

  docker-image:
    name: "Build docker image and generate pdf"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker buildx build -t testing --build-arg NODE_VERSION=${NODE_VERSION} ./docker
      - name: Generate pdf
        run: docker run -v `pwd`/examples/book:/work -w /work --rm testing honkit pdf
